### ISSUE TITLE
Plan not found

### ISSUE THREAD

**Issue by m-bryo** [iamraphson/vue-paystack#2]
I tested this a while back and it was working fine. And then, today, it keeps showing me plan not found.

**Comment by iamraphson** [comment]
Hello @m-bryo 

Can I see your code? thanks.

**Comment by m-bryo** [comment]
`              <paystack
                :amount="235000 * 100"
                :email="user.email"
                :paystackkey="paystackkey"
                :reference="'l' + String(Date.now()).substr(6) + user.role.ref.substr(Math.ceil(Math.random() * 20), 6) + Math.floor(Math.random() * 1000)"
                :callback="callback"
                :close="close"
                class="btn btn-sm btn-primary"
                text="N50,000/yr"
              ></paystack>`

Already fixed it though. It was a problem from my code, I had a global computed var with name `plan` and `currency`, so they were overriding. I had to fork your code and rename them
`   currency: {
              type: String,
              default: 'NGN'
          },
          plan: {
              type: String,
              default: ''
          },
` I've

**Comment by iamraphson** [comment]
@m-bryo you can send a PR tho. Thanks
