### ISSUE TITLE
PaystackPop is not defined

### ISSUE THREAD

**Issue by bigfielddigital** [iamraphson/vue-paystack#4]
I'm getting this warning after integrating your plugin.

PaystackPop is not defined.

Using Vuejs 2.

Thank you for such a great plugin.

**Comment by iamraphson** [comment]
let me see your code please.

**Comment by duleorlovic** [comment]
Just for reference, I got the same error when I include `<script src="https://js.paystack.co/v1/paystack.js"></script>` instead of  `<script src="https://js.paystack.co/v1/inline.js"></script>`, so check the docs carefully.

**Comment by alkadelik** [comment]
Hey @iamraphson were you able to resolve this? I'm getting the error too

**Comment by alkadelik** [comment]
> I'm getting this warning after integrating your plugin.
> 
> PaystackPop is not defined.
> 
> Using Vuejs 2.
> 
> Thank you for such a great plugin.

How did you solve this?

**Comment by ezechinwa** [comment]
1.  npm i @paystack/inline-js
2. import PaystackPop from '@paystack/inline-js';
